[2025-06-06T21:15:11.491+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-06T21:15:11.508+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 05_transform_data.run_dbt manual__2025-06-06T21:15:02.860598+00:00 [queued]>
[2025-06-06T21:15:11.515+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 05_transform_data.run_dbt manual__2025-06-06T21:15:02.860598+00:00 [queued]>
[2025-06-06T21:15:11.517+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-06T21:15:11.528+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt> on 2025-06-06 21:15:02.860598+00:00
[2025-06-06T21:15:11.532+0000] {standard_task_runner.py:72} INFO - Started process 6059 to run task
[2025-06-06T21:15:11.535+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '05_transform_data', 'run_dbt', 'manual__2025-06-06T21:15:02.860598+00:00', '--job-id', '480', '--raw', '--subdir', 'DAGS_FOLDER/05_transform_data.py', '--cfg-path', '/tmp/tmp3pqz75c5']
[2025-06-06T21:15:11.537+0000] {standard_task_runner.py:105} INFO - Job 480: Subtask run_dbt
[2025-06-06T21:15:11.587+0000] {task_command.py:467} INFO - Running <TaskInstance: 05_transform_data.run_dbt manual__2025-06-06T21:15:02.860598+00:00 [running]> on host 28e6a58e4107
[2025-06-06T21:15:11.672+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='05_transform_data' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T21:15:02.860598+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T21:15:02.860598+00:00'
[2025-06-06T21:15:11.673+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-06T21:15:13.193+0000] {logging_mixin.py:190} INFO - 21:15:13  Running with dbt=1.9.5
[2025-06-06T21:15:13.570+0000] {logging_mixin.py:190} INFO - 21:15:13  Registered adapter: postgres=1.9.0
[2025-06-06T21:15:14.829+0000] {logging_mixin.py:190} INFO - 21:15:14  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.e_commerce_sales.example
[2025-06-06T21:15:15.209+0000] {logging_mixin.py:190} INFO - 21:15:15  Found 15 models, 12 sources, 549 macros, 1 unit test
[2025-06-06T21:15:15.213+0000] {logging_mixin.py:190} INFO - 21:15:15
[2025-06-06T21:15:15.215+0000] {logging_mixin.py:190} INFO - 21:15:15  Concurrency: 4 threads (target='dev')
[2025-06-06T21:15:15.217+0000] {logging_mixin.py:190} INFO - 21:15:15
[2025-06-06T21:15:15.358+0000] {logging_mixin.py:190} INFO - 21:15:15  1 of 15 START sql incremental model sales.mercadolivre_orders_results .......... [RUN]
[2025-06-06T21:15:15.359+0000] {logging_mixin.py:190} INFO - 21:15:15  2 of 15 START sql incremental model sales.stg_shopee ........................... [RUN]
[2025-06-06T21:15:15.805+0000] {logging_mixin.py:190} INFO - 21:15:15  2 of 15 OK created sql incremental model sales.stg_shopee ...................... [MERGE 2875 in 0.44s]
[2025-06-06T21:15:15.811+0000] {logging_mixin.py:190} INFO - 21:15:15  3 of 15 START sql incremental model sales.shopee_new_id ........................ [RUN]
[2025-06-06T21:15:15.949+0000] {logging_mixin.py:190} INFO - 21:15:15  3 of 15 OK created sql incremental model sales.shopee_new_id ................... [MERGE 2875 in 0.13s]
[2025-06-06T21:15:15.956+0000] {logging_mixin.py:190} INFO - 21:15:15  4 of 15 START sql incremental model sales.shopee_orders_results ................ [RUN]
[2025-06-06T21:15:16.694+0000] {logging_mixin.py:190} INFO - 21:15:16  4 of 15 OK created sql incremental model sales.shopee_orders_results ........... [MERGE 2679 in 0.73s]
[2025-06-06T21:15:16.701+0000] {logging_mixin.py:190} INFO - 21:15:16  5 of 15 START sql incremental model sales.dim_shopee_buyer ..................... [RUN]
[2025-06-06T21:15:16.704+0000] {logging_mixin.py:190} INFO - 21:15:16  6 of 15 START sql incremental model sales.dim_shopee_date ...................... [RUN]
[2025-06-06T21:15:16.706+0000] {logging_mixin.py:190} INFO - 21:15:16  7 of 15 START sql incremental model sales.dim_shopee_orders_status ............. [RUN]
[2025-06-06T21:15:16.936+0000] {logging_mixin.py:190} INFO - 21:15:16  5 of 15 ERROR creating sql incremental model sales.dim_shopee_buyer ............ [ERROR in 0.23s]
[2025-06-06T21:15:16.954+0000] {logging_mixin.py:190} INFO - 21:15:16  8 of 15 START sql incremental model sales.dim_shopee_product ................... [RUN]
[2025-06-06T21:15:16.990+0000] {logging_mixin.py:190} INFO - 21:15:16  6 of 15 OK created sql incremental model sales.dim_shopee_date ................. [MERGE 2679 in 0.27s]
[2025-06-06T21:15:16.992+0000] {logging_mixin.py:190} INFO - 21:15:16  7 of 15 OK created sql incremental model sales.dim_shopee_orders_status ........ [MERGE 2679 in 0.27s]
[2025-06-06T21:15:17.003+0000] {logging_mixin.py:190} INFO - 21:15:17  9 of 15 START sql view model sales.sum_shopee_monthly_profit ................... [RUN]
[2025-06-06T21:15:17.005+0000] {logging_mixin.py:190} INFO - 21:15:17  10 of 15 START sql view model sales.sum_shopee_monthly_revenue ................. [RUN]
[2025-06-06T21:15:17.210+0000] {logging_mixin.py:190} INFO - 21:15:17  8 of 15 OK created sql incremental model sales.dim_shopee_product .............. [MERGE 180 in 0.25s]
[2025-06-06T21:15:17.216+0000] {logging_mixin.py:190} INFO - 21:15:17  9 of 15 OK created sql view model sales.sum_shopee_monthly_profit .............. [CREATE VIEW in 0.21s]
[2025-06-06T21:15:17.218+0000] {logging_mixin.py:190} INFO - 21:15:17  10 of 15 OK created sql view model sales.sum_shopee_monthly_revenue ............ [CREATE VIEW in 0.20s]
[2025-06-06T21:15:17.224+0000] {logging_mixin.py:190} INFO - 21:15:17  11 of 15 START sql view model sales.sum_shopee_products_sold ................... [RUN]
[2025-06-06T21:15:17.309+0000] {logging_mixin.py:190} INFO - 21:15:17  11 of 15 OK created sql view model sales.sum_shopee_products_sold .............. [CREATE VIEW in 0.08s]
[2025-06-06T21:15:18.291+0000] {logging_mixin.py:190} INFO - 21:15:18  1 of 15 OK created sql incremental model sales.mercadolivre_orders_results ..... [MERGE 190 in 2.93s]
[2025-06-06T21:15:18.299+0000] {logging_mixin.py:190} INFO - 21:15:18  12 of 15 START sql incremental model sales.dim_mercadolivre_buyer .............. [RUN]
[2025-06-06T21:15:18.300+0000] {logging_mixin.py:190} INFO - 21:15:18  13 of 15 START sql incremental model sales.dim_mercadolivre_date ............... [RUN]
[2025-06-06T21:15:18.302+0000] {logging_mixin.py:190} INFO - 21:15:18  14 of 15 START sql incremental model sales.dim_mercadolivre_orders_status ...... [RUN]
[2025-06-06T21:15:18.303+0000] {logging_mixin.py:190} INFO - 21:15:18  15 of 15 START sql incremental model sales.dim_mercadolivre_product ............ [RUN]
[2025-06-06T21:15:18.541+0000] {logging_mixin.py:190} INFO - 21:15:18  14 of 15 OK created sql incremental model sales.dim_mercadolivre_orders_status . [MERGE 190 in 0.23s]
[2025-06-06T21:15:18.556+0000] {logging_mixin.py:190} INFO - 21:15:18  12 of 15 OK created sql incremental model sales.dim_mercadolivre_buyer ......... [MERGE 188 in 0.25s]
[2025-06-06T21:15:19.854+0000] {logging_mixin.py:190} INFO - 21:15:19  13 of 15 OK created sql incremental model sales.dim_mercadolivre_date .......... [MERGE 190 in 1.55s]
[2025-06-06T21:15:21.219+0000] {logging_mixin.py:190} INFO - 21:15:21  15 of 15 OK created sql incremental model sales.dim_mercadolivre_product ....... [MERGE 65 in 2.91s]
[2025-06-06T21:15:21.245+0000] {logging_mixin.py:190} INFO - 21:15:21
[2025-06-06T21:15:21.247+0000] {logging_mixin.py:190} INFO - 21:15:21  Finished running 12 incremental models, 3 view models in 0 hours 0 minutes and 6.03 seconds (6.03s).
[2025-06-06T21:15:21.327+0000] {logging_mixin.py:190} INFO - 21:15:21
[2025-06-06T21:15:21.329+0000] {logging_mixin.py:190} INFO - 21:15:21  Completed with 1 error, 0 partial successes, and 0 warnings:
[2025-06-06T21:15:21.331+0000] {logging_mixin.py:190} INFO - 21:15:21
[2025-06-06T21:15:21.332+0000] {logging_mixin.py:190} INFO - 21:15:21    Database Error in model dim_shopee_buyer (models/core/dim_shopee_buyer.sql)
  MERGE command cannot affect row a second time
  HINT:  Ensure that not more than one source row matches any one target row.
  compiled code at target/run/e_commerce_sales/models/core/dim_shopee_buyer.sql
[2025-06-06T21:15:21.334+0000] {logging_mixin.py:190} INFO - 21:15:21
[2025-06-06T21:15:21.335+0000] {logging_mixin.py:190} INFO - 21:15:21  Done. PASS=14 WARN=0 ERROR=1 SKIP=0 TOTAL=15
[2025-06-06T21:15:22.210+0000] {logging_mixin.py:190} INFO - dbt run failed!
[2025-06-06T21:15:22.211+0000] {logging_mixin.py:190} INFO - None
[2025-06-06T21:15:22.212+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt_files/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-06-06T21:15:22.223+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=05_transform_data, task_id=run_dbt, run_id=manual__2025-06-06T21:15:02.860598+00:00, execution_date=20250606T211502, start_date=20250606T211511, end_date=20250606T211522
[2025-06-06T21:15:22.235+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-06T21:15:22.237+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 480 for task run_dbt (dbt run failed; 6059)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt_files/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-06-06T21:15:22.265+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-06T21:15:22.281+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-06T21:15:22.286+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
