[2025-05-21T18:39:06.684+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T18:39:06.705+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-05-21T18:39:04.912800+00:00 [queued]>
[2025-05-21T18:39:06.715+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-05-21T18:39:04.912800+00:00 [queued]>
[2025-05-21T18:39:06.716+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-21T18:39:06.728+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt> on 2025-05-21 18:39:04.912800+00:00
[2025-05-21T18:39:06.733+0000] {standard_task_runner.py:72} INFO - Started process 3417 to run task
[2025-05-21T18:39:06.736+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '04_transform_data', 'run_dbt', 'manual__2025-05-21T18:39:04.912800+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/04_transform_data.py', '--cfg-path', '/tmp/tmp3mcuvq07']
[2025-05-21T18:39:06.738+0000] {standard_task_runner.py:105} INFO - Job 106: Subtask run_dbt
[2025-05-21T18:39:06.789+0000] {task_command.py:467} INFO - Running <TaskInstance: 04_transform_data.run_dbt manual__2025-05-21T18:39:04.912800+00:00 [running]> on host e27e96d1841a
[2025-05-21T18:39:06.872+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='04_transform_data' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T18:39:04.912800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T18:39:04.912800+00:00'
[2025-05-21T18:39:06.874+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-21T18:39:09.076+0000] {logging_mixin.py:190} INFO - 18:39:09  Running with dbt=1.9.4
[2025-05-21T18:39:09.450+0000] {logging_mixin.py:190} INFO - 18:39:09  Registered adapter: postgres=1.9.0
[2025-05-21T18:39:10.593+0000] {logging_mixin.py:190} INFO - 18:39:10  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.e_commerce_sales.example
[2025-05-21T18:39:10.784+0000] {logging_mixin.py:190} INFO - 18:39:10  Found 10 models, 12 sources, 433 macros
[2025-05-21T18:39:10.788+0000] {logging_mixin.py:190} INFO - 18:39:10
[2025-05-21T18:39:10.789+0000] {logging_mixin.py:190} INFO - 18:39:10  Concurrency: 4 threads (target='dev')
[2025-05-21T18:39:10.791+0000] {logging_mixin.py:190} INFO - 18:39:10
[2025-05-21T18:39:10.940+0000] {logging_mixin.py:190} INFO - 18:39:10  1 of 10 START sql incremental model sales.mercadolivre_orders_results .......... [RUN]
[2025-05-21T18:39:10.943+0000] {logging_mixin.py:190} INFO - 18:39:10  2 of 10 START sql incremental model sales.shopee_new_id ........................ [RUN]
[2025-05-21T18:39:11.294+0000] {logging_mixin.py:190} INFO - 18:39:11  2 of 10 OK created sql incremental model sales.shopee_new_id ................... [MERGE 0 in 0.34s]
[2025-05-21T18:39:11.296+0000] {logging_mixin.py:190} INFO - 18:39:11  1 of 10 OK created sql incremental model sales.mercadolivre_orders_results ..... [MERGE 255 in 0.35s]
[2025-05-21T18:39:11.302+0000] {logging_mixin.py:190} INFO - 18:39:11  3 of 10 START sql incremental model sales.shopee_orders_results ................ [RUN]
[2025-05-21T18:39:11.307+0000] {logging_mixin.py:190} INFO - 18:39:11  4 of 10 START sql incremental model sales.dim_mercadolivre_buyer ............... [RUN]
[2025-05-21T18:39:11.308+0000] {logging_mixin.py:190} INFO - 18:39:11  5 of 10 START sql incremental model sales.dim_mercadolivre_product ............. [RUN]
[2025-05-21T18:39:11.310+0000] {logging_mixin.py:190} INFO - 18:39:11  6 of 10 START sql incremental model sales.mercadolivre_profits ................. [RUN]
[2025-05-21T18:39:11.483+0000] {logging_mixin.py:190} INFO - 18:39:11  4 of 10 ERROR creating sql incremental model sales.dim_mercadolivre_buyer ...... [ERROR in 0.17s]
[2025-05-21T18:39:11.595+0000] {logging_mixin.py:190} INFO - 18:39:11  5 of 10 OK created sql incremental model sales.dim_mercadolivre_product ........ [MERGE 250 in 0.28s]
[2025-05-21T18:39:11.599+0000] {logging_mixin.py:190} INFO - 18:39:11  3 of 10 OK created sql incremental model sales.shopee_orders_results ........... [MERGE 0 in 0.29s]
[2025-05-21T18:39:11.603+0000] {logging_mixin.py:190} INFO - 18:39:11  6 of 10 OK created sql incremental model sales.mercadolivre_profits ............ [MERGE 250 in 0.27s]
[2025-05-21T18:39:11.611+0000] {logging_mixin.py:190} INFO - 18:39:11  7 of 10 START sql incremental model sales.dim_shopee_buyer_id .................. [RUN]
[2025-05-21T18:39:11.613+0000] {logging_mixin.py:190} INFO - 18:39:11  8 of 10 START sql incremental model sales.dim_shopee_date ...................... [RUN]
[2025-05-21T18:39:11.614+0000] {logging_mixin.py:190} INFO - 18:39:11  9 of 10 START sql incremental model sales.dim_shopee_orders_status ............. [RUN]
[2025-05-21T18:39:11.616+0000] {logging_mixin.py:190} INFO - 18:39:11  10 of 10 START sql incremental model sales.dim_shopee_product .................. [RUN]
[2025-05-21T18:39:11.893+0000] {logging_mixin.py:190} INFO - 18:39:11  7 of 10 OK created sql incremental model sales.dim_shopee_buyer_id ............. [MERGE 0 in 0.27s]
[2025-05-21T18:39:11.897+0000] {logging_mixin.py:190} INFO - 18:39:11  8 of 10 OK created sql incremental model sales.dim_shopee_date ................. [MERGE 0 in 0.27s]
[2025-05-21T18:39:11.901+0000] {logging_mixin.py:190} INFO - 18:39:11  9 of 10 OK created sql incremental model sales.dim_shopee_orders_status ........ [MERGE 0 in 0.28s]
[2025-05-21T18:39:11.909+0000] {logging_mixin.py:190} INFO - 18:39:11  10 of 10 OK created sql incremental model sales.dim_shopee_product ............. [MERGE 0 in 0.28s]
[2025-05-21T18:39:11.935+0000] {logging_mixin.py:190} INFO - 18:39:11
[2025-05-21T18:39:11.937+0000] {logging_mixin.py:190} INFO - 18:39:11  Finished running 10 incremental models in 0 hours 0 minutes and 1.14 seconds (1.14s).
[2025-05-21T18:39:12.004+0000] {logging_mixin.py:190} INFO - 18:39:12
[2025-05-21T18:39:12.007+0000] {logging_mixin.py:190} INFO - 18:39:12  Completed with 1 error, 0 partial successes, and 0 warnings:
[2025-05-21T18:39:12.008+0000] {logging_mixin.py:190} INFO - 18:39:12
[2025-05-21T18:39:12.009+0000] {logging_mixin.py:190} INFO - 18:39:12    Database Error in model dim_mercadolivre_buyer (models/core/dim_mercadolivre_buyer.sql)
  syntax error at or near "."
  LINE 46:            buyer_id_shipping_id_buyer_data.street_number
                                                     ^
  compiled code at target/run/e_commerce_sales/models/core/dim_mercadolivre_buyer.sql
[2025-05-21T18:39:12.011+0000] {logging_mixin.py:190} INFO - 18:39:12
[2025-05-21T18:39:12.013+0000] {logging_mixin.py:190} INFO - 18:39:12  Done. PASS=9 WARN=0 ERROR=1 SKIP=0 TOTAL=10
[2025-05-21T18:39:13.444+0000] {logging_mixin.py:190} INFO - dbt run failed!
[2025-05-21T18:39:13.448+0000] {logging_mixin.py:190} INFO - None
[2025-05-21T18:39:13.453+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-05-21T18:39:13.468+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=04_transform_data, task_id=run_dbt, run_id=manual__2025-05-21T18:39:04.912800+00:00, execution_date=20250521T183904, start_date=20250521T183906, end_date=20250521T183913
[2025-05-21T18:39:13.481+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-21T18:39:13.482+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 106 for task run_dbt (dbt run failed; 3417)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-05-21T18:39:13.497+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-21T18:39:13.514+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T18:39:13.517+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
