[2025-05-15T19:50:16.111+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-15T19:50:16.130+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 01_extract_data.extract_ml manual__2025-05-15T19:50:13.174888+00:00 [queued]>
[2025-05-15T19:50:16.138+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 01_extract_data.extract_ml manual__2025-05-15T19:50:13.174888+00:00 [queued]>
[2025-05-15T19:50:16.140+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-15T19:50:16.154+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_ml> on 2025-05-15 19:50:13.174888+00:00
[2025-05-15T19:50:16.158+0000] {standard_task_runner.py:72} INFO - Started process 136 to run task
[2025-05-15T19:50:16.162+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '01_extract_data', 'extract_ml', 'manual__2025-05-15T19:50:13.174888+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/01_extract_dag.py', '--cfg-path', '/tmp/tmp41ib2te0']
[2025-05-15T19:50:16.164+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask extract_ml
[2025-05-15T19:50:16.223+0000] {task_command.py:467} INFO - Running <TaskInstance: 01_extract_data.extract_ml manual__2025-05-15T19:50:13.174888+00:00 [running]> on host ed37f07fa69f
[2025-05-15T19:50:16.303+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='01_extract_data' AIRFLOW_CTX_TASK_ID='extract_ml' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T19:50:13.174888+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-15T19:50:13.174888+00:00'
[2025-05-15T19:50:16.305+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-15T19:50:16.324+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/extraction/mercadolivre/script/extract_data.py", line 31, in extract_mercado
    access_token = token_file["access_token"]
KeyError: 'access_token'
[2025-05-15T19:50:16.337+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=01_extract_data, task_id=extract_ml, run_id=manual__2025-05-15T19:50:13.174888+00:00, execution_date=20250515T195013, start_date=20250515T195016, end_date=20250515T195016
[2025-05-15T19:50:16.347+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-15T19:50:16.348+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task extract_ml ('access_token'; 136)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/extraction/mercadolivre/script/extract_data.py", line 31, in extract_mercado
    access_token = token_file["access_token"]
KeyError: 'access_token'
[2025-05-15T19:50:16.376+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-15T19:50:16.393+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-15T19:50:16.395+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
