[2025-06-11T18:07:58.144+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-11T18:07:58.168+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 06_delete_entry_data.delete_files manual__2025-06-11T18:07:56.243104+00:00 [queued]>
[2025-06-11T18:07:58.179+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 06_delete_entry_data.delete_files manual__2025-06-11T18:07:56.243104+00:00 [queued]>
[2025-06-11T18:07:58.181+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-11T18:07:58.193+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): delete_files> on 2025-06-11 18:07:56.243104+00:00
[2025-06-11T18:07:58.198+0000] {standard_task_runner.py:72} INFO - Started process 106 to run task
[2025-06-11T18:07:58.201+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '06_delete_entry_data', 'delete_files', 'manual__2025-06-11T18:07:56.243104+00:00', '--job-id', '852', '--raw', '--subdir', 'DAGS_FOLDER/06_delete_files_tables.py', '--cfg-path', '/tmp/tmpr78zep9j']
[2025-06-11T18:07:58.203+0000] {standard_task_runner.py:105} INFO - Job 852: Subtask delete_files
[2025-06-11T18:07:58.265+0000] {task_command.py:467} INFO - Running <TaskInstance: 06_delete_entry_data.delete_files manual__2025-06-11T18:07:56.243104+00:00 [running]> on host 28e6a58e4107
[2025-06-11T18:07:58.374+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='06_delete_entry_data' AIRFLOW_CTX_TASK_ID='delete_files' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T18:07:56.243104+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T18:07:56.243104+00:00'
[2025-06-11T18:07:58.376+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-11T18:07:58.394+0000] {logging_mixin.py:190} INFO - Failed to delete file in ./extraction/mercadolivre/data/raw/*.json with error: [Errno 2] No such file or directory: 'extraction/mercadolivre/data/raw/*.json'
[2025-06-11T18:07:58.397+0000] {logging_mixin.py:190} INFO - Failed to delete file in ./extraction/mercadolivre/data/shipping_cost_ml/*.json with error: [Errno 2] No such file or directory: 'extraction/mercadolivre/data/shipping_cost_ml/*.json'
[2025-06-11T18:07:58.399+0000] {logging_mixin.py:190} INFO - Failed to delete file in ./extraction/shopee/data/raw/*.xlsx with error: [Errno 2] No such file or directory: 'extraction/shopee/data/raw/*.xlsx'
[2025-06-11T18:07:58.402+0000] {logging_mixin.py:190} INFO - Failed to delete file in ./extraction/mercadolivre/data/clean/shipping_ids_mercadolivre.csv with error: [Errno 2] No such file or directory: 'extraction/mercadolivre/data/clean/shipping_ids_mercadolivre.csv'
[2025-06-11T18:07:58.403+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-06-11T18:07:58.416+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-11T18:07:58.418+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=06_delete_entry_data, task_id=delete_files, run_id=manual__2025-06-11T18:07:56.243104+00:00, execution_date=20250611T180756, start_date=20250611T180758, end_date=20250611T180758
[2025-06-11T18:07:58.456+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-11T18:07:58.476+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-11T18:07:58.478+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
