[2025-06-06T18:35:20.191+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-06T18:35:20.209+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-06-06T18:35:11.162024+00:00 [queued]>
[2025-06-06T18:35:20.217+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-06-06T18:35:11.162024+00:00 [queued]>
[2025-06-06T18:35:20.220+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-06T18:35:20.233+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt> on 2025-06-06 18:35:11.162024+00:00
[2025-06-06T18:35:20.238+0000] {standard_task_runner.py:72} INFO - Started process 1494 to run task
[2025-06-06T18:35:20.241+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '04_transform_data', 'run_dbt', 'manual__2025-06-06T18:35:11.162024+00:00', '--job-id', '386', '--raw', '--subdir', 'DAGS_FOLDER/04_transform_data.py', '--cfg-path', '/tmp/tmp886r39rl']
[2025-06-06T18:35:20.243+0000] {standard_task_runner.py:105} INFO - Job 386: Subtask run_dbt
[2025-06-06T18:35:20.295+0000] {task_command.py:467} INFO - Running <TaskInstance: 04_transform_data.run_dbt manual__2025-06-06T18:35:11.162024+00:00 [running]> on host 28e6a58e4107
[2025-06-06T18:35:20.381+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='04_transform_data' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T18:35:11.162024+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T18:35:11.162024+00:00'
[2025-06-06T18:35:20.383+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-06T18:35:22.013+0000] {logging_mixin.py:190} INFO - 18:35:22  Running with dbt=1.9.5
[2025-06-06T18:35:22.405+0000] {logging_mixin.py:190} INFO - 18:35:22  Registered adapter: postgres=1.9.0
[2025-06-06T18:35:24.398+0000] {logging_mixin.py:190} INFO - 18:35:24  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.e_commerce_sales.example
[2025-06-06T18:35:24.624+0000] {logging_mixin.py:190} INFO - 18:35:24  Found 15 models, 12 sources, 549 macros, 1 unit test
[2025-06-06T18:35:24.628+0000] {logging_mixin.py:190} INFO - 18:35:24
[2025-06-06T18:35:24.630+0000] {logging_mixin.py:190} INFO - 18:35:24  Concurrency: 4 threads (target='dev')
[2025-06-06T18:35:24.632+0000] {logging_mixin.py:190} INFO - 18:35:24
[2025-06-06T18:35:24.770+0000] {logging_mixin.py:190} INFO - 18:35:24  1 of 15 START sql incremental model sales.mercadolivre_orders_results .......... [RUN]
[2025-06-06T18:35:24.771+0000] {logging_mixin.py:190} INFO - 18:35:24  2 of 15 START sql incremental model sales.stg_shopee ........................... [RUN]
[2025-06-06T18:35:25.175+0000] {logging_mixin.py:190} INFO - 18:35:25  2 of 15 OK created sql incremental model sales.stg_shopee ...................... [MERGE 0 in 0.39s]
[2025-06-06T18:35:25.177+0000] {logging_mixin.py:190} INFO - 18:35:25  1 of 15 OK created sql incremental model sales.mercadolivre_orders_results ..... [MERGE 190 in 0.40s]
[2025-06-06T18:35:25.182+0000] {logging_mixin.py:190} INFO - 18:35:25  3 of 15 START sql incremental model sales.shopee_new_id ........................ [RUN]
[2025-06-06T18:35:25.187+0000] {logging_mixin.py:190} INFO - 18:35:25  4 of 15 START sql incremental model sales.dim_mercadolivre_buyer ............... [RUN]
[2025-06-06T18:35:25.189+0000] {logging_mixin.py:190} INFO - 18:35:25  5 of 15 START sql incremental model sales.dim_mercadolivre_date ................ [RUN]
[2025-06-06T18:35:25.191+0000] {logging_mixin.py:190} INFO - 18:35:25  6 of 15 START sql incremental model sales.dim_mercadolivre_orders_status ....... [RUN]
[2025-06-06T18:35:25.446+0000] {logging_mixin.py:190} INFO - 18:35:25  3 of 15 OK created sql incremental model sales.shopee_new_id ................... [MERGE 0 in 0.26s]
[2025-06-06T18:35:25.468+0000] {logging_mixin.py:190} INFO - 18:35:25  7 of 15 START sql incremental model sales.dim_mercadolivre_product ............. [RUN]
[2025-06-06T18:35:25.503+0000] {logging_mixin.py:190} INFO - 18:35:25  4 of 15 OK created sql incremental model sales.dim_mercadolivre_buyer .......... [MERGE 188 in 0.31s]
[2025-06-06T18:35:25.507+0000] {logging_mixin.py:190} INFO - 18:35:25  6 of 15 OK created sql incremental model sales.dim_mercadolivre_orders_status .. [MERGE 190 in 0.30s]
[2025-06-06T18:35:25.525+0000] {logging_mixin.py:190} INFO - 18:35:25  8 of 15 START sql incremental model sales.shopee_orders_results ................ [RUN]
[2025-06-06T18:35:25.555+0000] {logging_mixin.py:190} INFO - 18:35:25  5 of 15 OK created sql incremental model sales.dim_mercadolivre_date ........... [MERGE 190 in 0.36s]
[2025-06-06T18:35:25.679+0000] {logging_mixin.py:190} INFO - 18:35:25  8 of 15 OK created sql incremental model sales.shopee_orders_results ........... [MERGE 0 in 0.15s]
[2025-06-06T18:35:25.689+0000] {logging_mixin.py:190} INFO - 18:35:25  9 of 15 START sql incremental model sales.dim_shopee_buyer ..................... [RUN]
[2025-06-06T18:35:25.691+0000] {logging_mixin.py:190} INFO - 18:35:25  10 of 15 START sql incremental model sales.dim_shopee_date ..................... [RUN]
[2025-06-06T18:35:25.692+0000] {logging_mixin.py:190} INFO - 18:35:25  11 of 15 START sql incremental model sales.dim_shopee_orders_status ............ [RUN]
[2025-06-06T18:35:25.733+0000] {logging_mixin.py:190} INFO - 18:35:25  7 of 15 OK created sql incremental model sales.dim_mercadolivre_product ........ [MERGE 65 in 0.25s]
[2025-06-06T18:35:25.748+0000] {logging_mixin.py:190} INFO - 18:35:25  12 of 15 START sql incremental model sales.dim_shopee_product .................. [RUN]
[2025-06-06T18:35:25.972+0000] {logging_mixin.py:190} INFO - 18:35:25  10 of 15 OK created sql incremental model sales.dim_shopee_date ................ [MERGE 0 in 0.27s]
[2025-06-06T18:35:25.990+0000] {logging_mixin.py:190} INFO - 18:35:25  13 of 15 START sql view model sales.sum_shopee_monthly_profit .................. [RUN]
[2025-06-06T18:35:25.998+0000] {logging_mixin.py:190} INFO - 18:35:25  9 of 15 OK created sql incremental model sales.dim_shopee_buyer ................ [MERGE 0 in 0.30s]
[2025-06-06T18:35:26.006+0000] {logging_mixin.py:190} INFO - 18:35:26  11 of 15 OK created sql incremental model sales.dim_shopee_orders_status ....... [MERGE 0 in 0.30s]
[2025-06-06T18:35:26.021+0000] {logging_mixin.py:190} INFO - 18:35:26  14 of 15 START sql view model sales.sum_shopee_monthly_revenue ................. [RUN]
[2025-06-06T18:35:26.066+0000] {logging_mixin.py:190} INFO - 18:35:26  12 of 15 OK created sql incremental model sales.dim_shopee_product ............. [MERGE 0 in 0.29s]
[2025-06-06T18:35:26.072+0000] {logging_mixin.py:190} INFO - 18:35:26  15 of 15 START sql view model sales.sum_shopee_products_sold ................... [RUN]
[2025-06-06T18:35:26.157+0000] {logging_mixin.py:190} INFO - 18:35:26  14 of 15 ERROR creating sql view model sales.sum_shopee_monthly_revenue ........ [ERROR in 0.13s]
[2025-06-06T18:35:26.207+0000] {logging_mixin.py:190} INFO - 18:35:26  13 of 15 OK created sql view model sales.sum_shopee_monthly_profit ............. [CREATE VIEW in 0.20s]
[2025-06-06T18:35:26.241+0000] {logging_mixin.py:190} INFO - 18:35:26  15 of 15 OK created sql view model sales.sum_shopee_products_sold .............. [CREATE VIEW in 0.16s]
[2025-06-06T18:35:26.274+0000] {logging_mixin.py:190} INFO - 18:35:26
[2025-06-06T18:35:26.276+0000] {logging_mixin.py:190} INFO - 18:35:26  Finished running 12 incremental models, 3 view models in 0 hours 0 minutes and 1.64 seconds (1.64s).
[2025-06-06T18:35:26.375+0000] {logging_mixin.py:190} INFO - 18:35:26
[2025-06-06T18:35:26.376+0000] {logging_mixin.py:190} INFO - 18:35:26  Completed with 1 error, 0 partial successes, and 0 warnings:
[2025-06-06T18:35:26.379+0000] {logging_mixin.py:190} INFO - 18:35:26
[2025-06-06T18:35:26.380+0000] {logging_mixin.py:190} INFO - 18:35:26    Database Error in model sum_shopee_monthly_revenue (models/core/sum_shopee_monthly_revenue.sql)
  function round(double precision, integer) does not exist
  LINE 10:     ROUND(SUM(results.qt * results.price), 2)
               ^
  HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
  compiled code at target/run/e_commerce_sales/models/core/sum_shopee_monthly_revenue.sql
[2025-06-06T18:35:26.382+0000] {logging_mixin.py:190} INFO - 18:35:26
[2025-06-06T18:35:26.383+0000] {logging_mixin.py:190} INFO - 18:35:26  Done. PASS=14 WARN=0 ERROR=1 SKIP=0 TOTAL=15
[2025-06-06T18:35:27.254+0000] {logging_mixin.py:190} INFO - dbt run failed!
[2025-06-06T18:35:27.255+0000] {logging_mixin.py:190} INFO - None
[2025-06-06T18:35:27.256+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt_files/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-06-06T18:35:27.268+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=04_transform_data, task_id=run_dbt, run_id=manual__2025-06-06T18:35:11.162024+00:00, execution_date=20250606T183511, start_date=20250606T183520, end_date=20250606T183527
[2025-06-06T18:35:27.280+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-06T18:35:27.281+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 386 for task run_dbt (dbt run failed; 1494)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt_files/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-06-06T18:35:27.324+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-06T18:35:27.343+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-06T18:35:27.346+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
