[2025-05-22T18:36:41.622+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-22T18:36:41.647+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-05-22T18:36:39.404209+00:00 [queued]>
[2025-05-22T18:36:41.658+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-05-22T18:36:39.404209+00:00 [queued]>
[2025-05-22T18:36:41.660+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-22T18:36:41.675+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt> on 2025-05-22 18:36:39.404209+00:00
[2025-05-22T18:36:41.681+0000] {standard_task_runner.py:72} INFO - Started process 3333 to run task
[2025-05-22T18:36:41.684+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '04_transform_data', 'run_dbt', 'manual__2025-05-22T18:36:39.404209+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/04_transform_data.py', '--cfg-path', '/tmp/tmpwqqcm5m3']
[2025-05-22T18:36:41.687+0000] {standard_task_runner.py:105} INFO - Job 195: Subtask run_dbt
[2025-05-22T18:36:41.747+0000] {task_command.py:467} INFO - Running <TaskInstance: 04_transform_data.run_dbt manual__2025-05-22T18:36:39.404209+00:00 [running]> on host e27e96d1841a
[2025-05-22T18:36:41.843+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='04_transform_data' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T18:36:39.404209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-22T18:36:39.404209+00:00'
[2025-05-22T18:36:41.845+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-22T18:36:43.799+0000] {logging_mixin.py:190} INFO - 18:36:43  Running with dbt=1.9.4
[2025-05-22T18:36:44.140+0000] {logging_mixin.py:190} INFO - 18:36:44  Registered adapter: postgres=1.9.0
[2025-05-22T18:36:45.235+0000] {logging_mixin.py:190} INFO - 18:36:45  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.e_commerce_sales.example
[2025-05-22T18:36:45.403+0000] {logging_mixin.py:190} INFO - 18:36:45  Found 11 models, 12 sources, 433 macros
[2025-05-22T18:36:45.407+0000] {logging_mixin.py:190} INFO - 18:36:45
[2025-05-22T18:36:45.409+0000] {logging_mixin.py:190} INFO - 18:36:45  Concurrency: 4 threads (target='dev')
[2025-05-22T18:36:45.411+0000] {logging_mixin.py:190} INFO - 18:36:45
[2025-05-22T18:36:45.544+0000] {logging_mixin.py:190} INFO - 18:36:45  1 of 11 START sql incremental model sales.mercadolivre_orders_results .......... [RUN]
[2025-05-22T18:36:45.546+0000] {logging_mixin.py:190} INFO - 18:36:45  2 of 11 START sql incremental model sales.shopee_new_id ........................ [RUN]
[2025-05-22T18:36:45.663+0000] {logging_mixin.py:190} INFO - 18:36:45  1 of 11 ERROR creating sql incremental model sales.mercadolivre_orders_results . [ERROR in 0.09s]
[2025-05-22T18:36:45.672+0000] {logging_mixin.py:190} INFO - 18:36:45  3 of 11 SKIP relation sales.dim_mercadolivre_buyer ............................. [SKIP]
[2025-05-22T18:36:45.675+0000] {logging_mixin.py:190} INFO - 18:36:45  4 of 11 SKIP relation sales.dim_mercadolivre_date .............................. [SKIP]
[2025-05-22T18:36:45.676+0000] {logging_mixin.py:190} INFO - 18:36:45  5 of 11 SKIP relation sales.dim_mercadolivre_orders_status ..................... [SKIP]
[2025-05-22T18:36:45.682+0000] {logging_mixin.py:190} INFO - 18:36:45  6 of 11 SKIP relation sales.dim_mercadolivre_product ........................... [SKIP]
[2025-05-22T18:36:45.815+0000] {logging_mixin.py:190} INFO - 18:36:45  2 of 11 OK created sql incremental model sales.shopee_new_id ................... [MERGE 0 in 0.26s]
[2025-05-22T18:36:45.819+0000] {logging_mixin.py:190} INFO - 18:36:45  7 of 11 START sql incremental model sales.shopee_orders_results ................ [RUN]
[2025-05-22T18:36:45.929+0000] {logging_mixin.py:190} INFO - 18:36:45  7 of 11 OK created sql incremental model sales.shopee_orders_results ........... [MERGE 0 in 0.11s]
[2025-05-22T18:36:45.935+0000] {logging_mixin.py:190} INFO - 18:36:45  8 of 11 START sql incremental model sales.dim_shopee_buyer_id .................. [RUN]
[2025-05-22T18:36:45.937+0000] {logging_mixin.py:190} INFO - 18:36:45  9 of 11 START sql incremental model sales.dim_shopee_date ...................... [RUN]
[2025-05-22T18:36:45.938+0000] {logging_mixin.py:190} INFO - 18:36:45  10 of 11 START sql incremental model sales.dim_shopee_orders_status ............ [RUN]
[2025-05-22T18:36:45.940+0000] {logging_mixin.py:190} INFO - 18:36:45  11 of 11 START sql incremental model sales.dim_shopee_product .................. [RUN]
[2025-05-22T18:36:46.195+0000] {logging_mixin.py:190} INFO - 18:36:46  8 of 11 OK created sql incremental model sales.dim_shopee_buyer_id ............. [MERGE 0 in 0.25s]
[2025-05-22T18:36:46.210+0000] {logging_mixin.py:190} INFO - 18:36:46  11 of 11 OK created sql incremental model sales.dim_shopee_product ............. [MERGE 0 in 0.26s]
[2025-05-22T18:36:46.212+0000] {logging_mixin.py:190} INFO - 18:36:46  10 of 11 OK created sql incremental model sales.dim_shopee_orders_status ....... [MERGE 0 in 0.26s]
[2025-05-22T18:36:46.214+0000] {logging_mixin.py:190} INFO - 18:36:46  9 of 11 OK created sql incremental model sales.dim_shopee_date ................. [MERGE 0 in 0.27s]
[2025-05-22T18:36:46.239+0000] {logging_mixin.py:190} INFO - 18:36:46
[2025-05-22T18:36:46.240+0000] {logging_mixin.py:190} INFO - 18:36:46  Finished running 11 incremental models in 0 hours 0 minutes and 0.83 seconds (0.83s).
[2025-05-22T18:36:46.300+0000] {logging_mixin.py:190} INFO - 18:36:46
[2025-05-22T18:36:46.302+0000] {logging_mixin.py:190} INFO - 18:36:46  Completed with 1 error, 0 partial successes, and 0 warnings:
[2025-05-22T18:36:46.303+0000] {logging_mixin.py:190} INFO - 18:36:46
[2025-05-22T18:36:46.304+0000] {logging_mixin.py:190} INFO - 18:36:46    Compilation Error in model mercadolivre_orders_results (models/core/mercadolivre_orders_results.sql)
  'dbt_utils' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-05-22T18:36:46.306+0000] {logging_mixin.py:190} INFO - 18:36:46
[2025-05-22T18:36:46.307+0000] {logging_mixin.py:190} INFO - 18:36:46  Done. PASS=6 WARN=0 ERROR=1 SKIP=4 TOTAL=11
[2025-05-22T18:36:47.212+0000] {logging_mixin.py:190} INFO - dbt run failed!
[2025-05-22T18:36:47.213+0000] {logging_mixin.py:190} INFO - None
[2025-05-22T18:36:47.213+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-05-22T18:36:47.223+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=04_transform_data, task_id=run_dbt, run_id=manual__2025-05-22T18:36:39.404209+00:00, execution_date=20250522T183639, start_date=20250522T183641, end_date=20250522T183647
[2025-05-22T18:36:47.236+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-22T18:36:47.238+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 195 for task run_dbt (dbt run failed; 3333)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-05-22T18:36:47.282+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-22T18:36:47.299+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-22T18:36:47.302+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
