[2025-05-29T13:09:54.025+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-29T13:09:54.043+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 01_extract_data.ml_access_token manual__2025-05-29T13:09:52.620409+00:00 [queued]>
[2025-05-29T13:09:54.051+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 01_extract_data.ml_access_token manual__2025-05-29T13:09:52.620409+00:00 [queued]>
[2025-05-29T13:09:54.053+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-29T13:09:54.065+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ml_access_token> on 2025-05-29 13:09:52.620409+00:00
[2025-05-29T13:09:54.069+0000] {standard_task_runner.py:72} INFO - Started process 108 to run task
[2025-05-29T13:09:54.072+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '01_extract_data', 'ml_access_token', 'manual__2025-05-29T13:09:52.620409+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/01_extract_dag.py', '--cfg-path', '/tmp/tmpp9sih00y']
[2025-05-29T13:09:54.074+0000] {standard_task_runner.py:105} INFO - Job 266: Subtask ml_access_token
[2025-05-29T13:09:54.133+0000] {task_command.py:467} INFO - Running <TaskInstance: 01_extract_data.ml_access_token manual__2025-05-29T13:09:52.620409+00:00 [running]> on host 4465d1a8efb0
[2025-05-29T13:09:54.217+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='01_extract_data' AIRFLOW_CTX_TASK_ID='ml_access_token' AIRFLOW_CTX_EXECUTION_DATE='2025-05-29T13:09:52.620409+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-29T13:09:52.620409+00:00'
[2025-05-29T13:09:54.219+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-29T13:09:54.251+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/extraction/mercadolivre/script/get_access_token.py", line 10, in get_access_token
    client_id = os.environ["CLIENT_ID"]
  File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'CLIENT_ID'
[2025-05-29T13:09:54.266+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=01_extract_data, task_id=ml_access_token, run_id=manual__2025-05-29T13:09:52.620409+00:00, execution_date=20250529T130952, start_date=20250529T130954, end_date=20250529T130954
[2025-05-29T13:09:54.276+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-29T13:09:54.278+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 266 for task ml_access_token ('CLIENT_ID'; 108)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/extraction/mercadolivre/script/get_access_token.py", line 10, in get_access_token
    client_id = os.environ["CLIENT_ID"]
  File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'CLIENT_ID'
[2025-05-29T13:09:54.287+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-29T13:09:54.306+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-29T13:09:54.311+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
