[2025-05-16T12:59:06.648+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-16T12:59:06.672+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-05-16T12:59:05.495518+00:00 [queued]>
[2025-05-16T12:59:06.683+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-05-16T12:59:05.495518+00:00 [queued]>
[2025-05-16T12:59:06.684+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-16T12:59:06.699+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt> on 2025-05-16 12:59:05.495518+00:00
[2025-05-16T12:59:06.704+0000] {standard_task_runner.py:72} INFO - Started process 88 to run task
[2025-05-16T12:59:06.708+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '04_transform_data', 'run_dbt', 'manual__2025-05-16T12:59:05.495518+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/04_transform_data.py', '--cfg-path', '/tmp/tmp8begybpj']
[2025-05-16T12:59:06.711+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask run_dbt
[2025-05-16T12:59:06.767+0000] {task_command.py:467} INFO - Running <TaskInstance: 04_transform_data.run_dbt manual__2025-05-16T12:59:05.495518+00:00 [running]> on host b43b94ab59b1
[2025-05-16T12:59:06.850+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='04_transform_data' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T12:59:05.495518+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-16T12:59:05.495518+00:00'
[2025-05-16T12:59:06.852+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-16T12:59:08.780+0000] {logging_mixin.py:190} INFO - 12:59:08  Running with dbt=1.9.4
[2025-05-16T12:59:09.146+0000] {logging_mixin.py:190} INFO - 12:59:09  Registered adapter: postgres=1.9.0
[2025-05-16T12:59:09.555+0000] {logging_mixin.py:190} INFO - 12:59:09  Unable to do partial parsing because profile has changed
[2025-05-16T12:59:11.300+0000] {logging_mixin.py:190} INFO - 12:59:11  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.e_commerce_sales.example
[2025-05-16T12:59:11.484+0000] {logging_mixin.py:190} INFO - 12:59:11  Found 5 models, 12 sources, 433 macros
[2025-05-16T12:59:11.488+0000] {logging_mixin.py:190} INFO - 12:59:11
[2025-05-16T12:59:11.489+0000] {logging_mixin.py:190} INFO - 12:59:11  Concurrency: 4 threads (target='dev')
[2025-05-16T12:59:11.491+0000] {logging_mixin.py:190} INFO - 12:59:11
[2025-05-16T12:59:11.543+0000] {logging_mixin.py:190} INFO - 12:59:11
[2025-05-16T12:59:11.545+0000] {logging_mixin.py:190} INFO - 12:59:11  Finished running  in 0 hours 0 minutes and 0.05 seconds (0.05s).
[2025-05-16T12:59:11.546+0000] {logging_mixin.py:190} INFO - 12:59:11  Encountered an error:
Database Error
  connection to server at "localhost" (::1), port 5432 failed: Connection refused
  	Is the server running on that host and accepting TCP/IP connections?
  connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
  	Is the server running on that host and accepting TCP/IP connections?
[2025-05-16T12:59:12.272+0000] {logging_mixin.py:190} INFO - dbt run failed!
[2025-05-16T12:59:12.273+0000] {logging_mixin.py:190} INFO - Database Error
  connection to server at "localhost" (::1), port 5432 failed: Connection refused
  	Is the server running on that host and accepting TCP/IP connections?
  connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
  	Is the server running on that host and accepting TCP/IP connections?
  
[2025-05-16T12:59:12.274+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-05-16T12:59:12.284+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=04_transform_data, task_id=run_dbt, run_id=manual__2025-05-16T12:59:05.495518+00:00, execution_date=20250516T125905, start_date=20250516T125906, end_date=20250516T125912
[2025-05-16T12:59:12.301+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-16T12:59:12.303+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 25 for task run_dbt (dbt run failed; 88)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-05-16T12:59:12.350+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-16T12:59:12.366+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-16T12:59:12.369+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
