[2025-05-22T18:39:26.334+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-22T18:39:26.353+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-05-22T18:39:24.628257+00:00 [queued]>
[2025-05-22T18:39:26.362+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-05-22T18:39:24.628257+00:00 [queued]>
[2025-05-22T18:39:26.363+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-22T18:39:26.376+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt> on 2025-05-22 18:39:24.628257+00:00
[2025-05-22T18:39:26.381+0000] {standard_task_runner.py:72} INFO - Started process 3382 to run task
[2025-05-22T18:39:26.384+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '04_transform_data', 'run_dbt', 'manual__2025-05-22T18:39:24.628257+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/04_transform_data.py', '--cfg-path', '/tmp/tmpznzhdwn5']
[2025-05-22T18:39:26.386+0000] {standard_task_runner.py:105} INFO - Job 196: Subtask run_dbt
[2025-05-22T18:39:26.440+0000] {task_command.py:467} INFO - Running <TaskInstance: 04_transform_data.run_dbt manual__2025-05-22T18:39:24.628257+00:00 [running]> on host e27e96d1841a
[2025-05-22T18:39:26.530+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='04_transform_data' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T18:39:24.628257+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-22T18:39:24.628257+00:00'
[2025-05-22T18:39:26.532+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-22T18:39:28.210+0000] {logging_mixin.py:190} INFO - 18:39:28  Running with dbt=1.9.4
[2025-05-22T18:39:28.442+0000] {logging_mixin.py:190} INFO - 18:39:28  Encountered an error:
'version'
[2025-05-22T18:39:28.447+0000] {logging_mixin.py:190} INFO - 18:39:28  Traceback (most recent call last):
  File "/home/***/.local/lib/python3.9/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/dbt/cli/requires.py", line 235, in wrapper
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/dbt/cli/requires.py", line 251, in wrapper
    project = load_project(
  File "/home/***/.local/lib/python3.9/site-packages/dbt/config/runtime.py", line 59, in load_project
    project = Project.from_project_root(
  File "/home/***/.local/lib/python3.9/site-packages/dbt/config/project.py", line 752, in from_project_root
    return partial.render(renderer)
  File "/home/***/.local/lib/python3.9/site-packages/dbt/config/project.py", line 321, in render
    return self.create_project(rendered)
  File "/home/***/.local/lib/python3.9/site-packages/dbt/config/project.py", line 468, in create_project
    packages: PackageConfig = package_config_from_data(
  File "/home/***/.local/lib/python3.9/site-packages/dbt/config/project.py", line 139, in package_config_from_data
    PackageConfig.validate(packages_data)
  File "/home/***/.local/lib/python3.9/site-packages/dbt/contracts/project.py", line 129, in validate
    if not package["version"]:
KeyError: 'version'
[2025-05-22T18:39:29.187+0000] {logging_mixin.py:190} INFO - dbt run failed!
[2025-05-22T18:39:29.191+0000] {logging_mixin.py:190} INFO - 'version'
[2025-05-22T18:39:29.195+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-05-22T18:39:29.211+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=04_transform_data, task_id=run_dbt, run_id=manual__2025-05-22T18:39:24.628257+00:00, execution_date=20250522T183924, start_date=20250522T183926, end_date=20250522T183929
[2025-05-22T18:39:29.224+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-22T18:39:29.225+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 196 for task run_dbt (dbt run failed; 3382)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-05-22T18:39:29.250+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-22T18:39:29.270+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-22T18:39:29.273+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
