[2025-06-06T18:31:16.145+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-06T18:31:16.166+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-06-06T18:31:06.458625+00:00 [queued]>
[2025-06-06T18:31:16.174+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-06-06T18:31:06.458625+00:00 [queued]>
[2025-06-06T18:31:16.176+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-06T18:31:16.192+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt> on 2025-06-06 18:31:06.458625+00:00
[2025-06-06T18:31:16.197+0000] {standard_task_runner.py:72} INFO - Started process 1393 to run task
[2025-06-06T18:31:16.200+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '04_transform_data', 'run_dbt', 'manual__2025-06-06T18:31:06.458625+00:00', '--job-id', '382', '--raw', '--subdir', 'DAGS_FOLDER/04_transform_data.py', '--cfg-path', '/tmp/tmp2u1j2krj']
[2025-06-06T18:31:16.201+0000] {standard_task_runner.py:105} INFO - Job 382: Subtask run_dbt
[2025-06-06T18:31:16.255+0000] {task_command.py:467} INFO - Running <TaskInstance: 04_transform_data.run_dbt manual__2025-06-06T18:31:06.458625+00:00 [running]> on host 28e6a58e4107
[2025-06-06T18:31:16.345+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='04_transform_data' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T18:31:06.458625+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T18:31:06.458625+00:00'
[2025-06-06T18:31:16.346+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-06T18:31:18.046+0000] {logging_mixin.py:190} INFO - 18:31:18  Running with dbt=1.9.5
[2025-06-06T18:31:18.450+0000] {logging_mixin.py:190} INFO - 18:31:18  Registered adapter: postgres=1.9.0
[2025-06-06T18:31:20.424+0000] {logging_mixin.py:190} INFO - 18:31:20  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.e_commerce_sales.example
[2025-06-06T18:31:20.645+0000] {logging_mixin.py:190} INFO - 18:31:20  Found 15 models, 12 sources, 549 macros, 1 unit test
[2025-06-06T18:31:20.651+0000] {logging_mixin.py:190} INFO - 18:31:20
[2025-06-06T18:31:20.653+0000] {logging_mixin.py:190} INFO - 18:31:20  Concurrency: 4 threads (target='dev')
[2025-06-06T18:31:20.655+0000] {logging_mixin.py:190} INFO - 18:31:20
[2025-06-06T18:31:20.811+0000] {logging_mixin.py:190} INFO - 18:31:20  1 of 15 START sql incremental model sales.mercadolivre_orders_results .......... [RUN]
[2025-06-06T18:31:20.813+0000] {logging_mixin.py:190} INFO - 18:31:20  2 of 15 START sql incremental model sales.stg_shopee ........................... [RUN]
[2025-06-06T18:31:20.816+0000] {logging_mixin.py:190} INFO - 18:31:20  3 of 15 START sql view model sales.sum_shopee_monthly_profit ................... [RUN]
[2025-06-06T18:31:20.817+0000] {logging_mixin.py:190} INFO - 18:31:20  4 of 15 START sql view model sales.sum_shopee_monthly_revenue .................. [RUN]
[2025-06-06T18:31:21.241+0000] {logging_mixin.py:190} INFO - 18:31:21  4 of 15 ERROR creating sql view model sales.sum_shopee_monthly_revenue ......... [ERROR in 0.41s]
[2025-06-06T18:31:21.329+0000] {logging_mixin.py:190} INFO - 18:31:21  3 of 15 OK created sql view model sales.sum_shopee_monthly_profit .............. [CREATE VIEW in 0.50s]
[2025-06-06T18:31:21.353+0000] {logging_mixin.py:190} INFO - 18:31:21  2 of 15 OK created sql incremental model sales.stg_shopee ...................... [MERGE 0 in 0.53s]
[2025-06-06T18:31:21.355+0000] {logging_mixin.py:190} INFO - 18:31:21  1 of 15 OK created sql incremental model sales.mercadolivre_orders_results ..... [MERGE 190 in 0.54s]
[2025-06-06T18:31:21.363+0000] {logging_mixin.py:190} INFO - 18:31:21  5 of 15 START sql incremental model sales.shopee_new_id ........................ [RUN]
[2025-06-06T18:31:21.364+0000] {logging_mixin.py:190} INFO - 18:31:21  6 of 15 START sql incremental model sales.dim_mercadolivre_buyer ............... [RUN]
[2025-06-06T18:31:21.366+0000] {logging_mixin.py:190} INFO - 18:31:21  7 of 15 START sql incremental model sales.dim_mercadolivre_date ................ [RUN]
[2025-06-06T18:31:21.367+0000] {logging_mixin.py:190} INFO - 18:31:21  8 of 15 START sql incremental model sales.dim_mercadolivre_orders_status ....... [RUN]
[2025-06-06T18:31:21.630+0000] {logging_mixin.py:190} INFO - 18:31:21  5 of 15 OK created sql incremental model sales.shopee_new_id ................... [MERGE 0 in 0.26s]
[2025-06-06T18:31:21.648+0000] {logging_mixin.py:190} INFO - 18:31:21  9 of 15 START sql incremental model sales.dim_mercadolivre_product ............. [RUN]
[2025-06-06T18:31:21.661+0000] {logging_mixin.py:190} INFO - 18:31:21  6 of 15 OK created sql incremental model sales.dim_mercadolivre_buyer .......... [MERGE 188 in 0.29s]
[2025-06-06T18:31:21.687+0000] {logging_mixin.py:190} INFO - 18:31:21  8 of 15 OK created sql incremental model sales.dim_mercadolivre_orders_status .. [MERGE 190 in 0.31s]
[2025-06-06T18:31:21.689+0000] {logging_mixin.py:190} INFO - 18:31:21  10 of 15 START sql incremental model sales.shopee_orders_results ............... [RUN]
[2025-06-06T18:31:21.727+0000] {logging_mixin.py:190} INFO - 18:31:21  7 of 15 OK created sql incremental model sales.dim_mercadolivre_date ........... [MERGE 190 in 0.34s]
[2025-06-06T18:31:21.846+0000] {logging_mixin.py:190} INFO - 18:31:21  10 of 15 OK created sql incremental model sales.shopee_orders_results .......... [MERGE 0 in 0.14s]
[2025-06-06T18:31:21.859+0000] {logging_mixin.py:190} INFO - 18:31:21  11 of 15 START sql incremental model sales.dim_shopee_buyer .................... [RUN]
[2025-06-06T18:31:21.861+0000] {logging_mixin.py:190} INFO - 18:31:21  12 of 15 START sql incremental model sales.dim_shopee_date ..................... [RUN]
[2025-06-06T18:31:21.864+0000] {logging_mixin.py:190} INFO - 18:31:21  13 of 15 START sql incremental model sales.dim_shopee_orders_status ............ [RUN]
[2025-06-06T18:31:21.947+0000] {logging_mixin.py:190} INFO - 18:31:21  9 of 15 OK created sql incremental model sales.dim_mercadolivre_product ........ [MERGE 65 in 0.29s]
[2025-06-06T18:31:21.953+0000] {logging_mixin.py:190} INFO - 18:31:21  14 of 15 START sql incremental model sales.dim_shopee_product .................. [RUN]
[2025-06-06T18:31:22.143+0000] {logging_mixin.py:190} INFO - 18:31:22  12 of 15 OK created sql incremental model sales.dim_shopee_date ................ [MERGE 0 in 0.27s]
[2025-06-06T18:31:22.145+0000] {logging_mixin.py:190} INFO - 18:31:22  11 of 15 OK created sql incremental model sales.dim_shopee_buyer ............... [MERGE 0 in 0.27s]
[2025-06-06T18:31:22.154+0000] {logging_mixin.py:190} INFO - 18:31:22  13 of 15 OK created sql incremental model sales.dim_shopee_orders_status ....... [MERGE 0 in 0.28s]
[2025-06-06T18:31:22.180+0000] {logging_mixin.py:190} INFO - 18:31:22  14 of 15 OK created sql incremental model sales.dim_shopee_product ............. [MERGE 0 in 0.21s]
[2025-06-06T18:31:22.186+0000] {logging_mixin.py:190} INFO - 18:31:22  15 of 15 START sql view model sales.sum_shopee_products_sold ................... [RUN]
[2025-06-06T18:31:22.274+0000] {logging_mixin.py:190} INFO - 18:31:22  15 of 15 OK created sql view model sales.sum_shopee_products_sold .............. [CREATE VIEW in 0.09s]
[2025-06-06T18:31:22.300+0000] {logging_mixin.py:190} INFO - 18:31:22
[2025-06-06T18:31:22.302+0000] {logging_mixin.py:190} INFO - 18:31:22  Finished running 12 incremental models, 3 view models in 0 hours 0 minutes and 1.64 seconds (1.64s).
[2025-06-06T18:31:22.382+0000] {logging_mixin.py:190} INFO - 18:31:22
[2025-06-06T18:31:22.383+0000] {logging_mixin.py:190} INFO - 18:31:22  Completed with 1 error, 0 partial successes, and 0 warnings:
[2025-06-06T18:31:22.385+0000] {logging_mixin.py:190} INFO - 18:31:22
[2025-06-06T18:31:22.386+0000] {logging_mixin.py:190} INFO - 18:31:22    Database Error in model sum_shopee_monthly_revenue (models/core/sum_shopee_monthly_revenue.sql)
  function round(double precision, integer) does not exist
  LINE 10:     ROUND(SUM(results.qt * results.price), 2)
               ^
  HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
  compiled code at target/run/e_commerce_sales/models/core/sum_shopee_monthly_revenue.sql
[2025-06-06T18:31:22.388+0000] {logging_mixin.py:190} INFO - 18:31:22
[2025-06-06T18:31:22.390+0000] {logging_mixin.py:190} INFO - 18:31:22  Done. PASS=14 WARN=0 ERROR=1 SKIP=0 TOTAL=15
[2025-06-06T18:31:23.250+0000] {logging_mixin.py:190} INFO - dbt run failed!
[2025-06-06T18:31:23.252+0000] {logging_mixin.py:190} INFO - None
[2025-06-06T18:31:23.253+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt_files/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-06-06T18:31:23.265+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=04_transform_data, task_id=run_dbt, run_id=manual__2025-06-06T18:31:06.458625+00:00, execution_date=20250606T183106, start_date=20250606T183116, end_date=20250606T183123
[2025-06-06T18:31:23.282+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-06T18:31:23.282+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 382 for task run_dbt (dbt run failed; 1393)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt_files/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-06-06T18:31:23.321+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-06T18:31:23.338+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-06T18:31:23.341+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
