[2025-06-05T19:46:07.317+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-05T19:46:07.338+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-06-05T19:45:58.567017+00:00 [queued]>
[2025-06-05T19:46:07.348+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 04_transform_data.run_dbt manual__2025-06-05T19:45:58.567017+00:00 [queued]>
[2025-06-05T19:46:07.349+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-05T19:46:07.364+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt> on 2025-06-05 19:45:58.567017+00:00
[2025-06-05T19:46:07.368+0000] {standard_task_runner.py:72} INFO - Started process 2262 to run task
[2025-06-05T19:46:07.372+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '04_transform_data', 'run_dbt', 'manual__2025-06-05T19:45:58.567017+00:00', '--job-id', '347', '--raw', '--subdir', 'DAGS_FOLDER/04_transform_data.py', '--cfg-path', '/tmp/tmp7u1wr4ys']
[2025-06-05T19:46:07.374+0000] {standard_task_runner.py:105} INFO - Job 347: Subtask run_dbt
[2025-06-05T19:46:07.427+0000] {task_command.py:467} INFO - Running <TaskInstance: 04_transform_data.run_dbt manual__2025-06-05T19:45:58.567017+00:00 [running]> on host 28e6a58e4107
[2025-06-05T19:46:07.514+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='04_transform_data' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-06-05T19:45:58.567017+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-05T19:45:58.567017+00:00'
[2025-06-05T19:46:07.519+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-05T19:46:09.352+0000] {logging_mixin.py:190} INFO - 19:46:09  Running with dbt=1.9.5
[2025-06-05T19:46:09.734+0000] {logging_mixin.py:190} INFO - 19:46:09  Registered adapter: postgres=1.9.0
[2025-06-05T19:46:10.944+0000] {logging_mixin.py:190} INFO - 19:46:10  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.e_commerce_sales.example
[2025-06-05T19:46:11.339+0000] {logging_mixin.py:190} INFO - 19:46:11  Found 11 models, 12 sources, 549 macros, 1 unit test
[2025-06-05T19:46:11.344+0000] {logging_mixin.py:190} INFO - 19:46:11
[2025-06-05T19:46:11.346+0000] {logging_mixin.py:190} INFO - 19:46:11  Concurrency: 4 threads (target='dev')
[2025-06-05T19:46:11.348+0000] {logging_mixin.py:190} INFO - 19:46:11
[2025-06-05T19:46:11.485+0000] {logging_mixin.py:190} INFO - 19:46:11  1 of 11 START sql incremental model sales.dim_shopee_product ................... [RUN]
[2025-06-05T19:46:11.487+0000] {logging_mixin.py:190} INFO - 19:46:11  2 of 11 START sql incremental model sales.mercadolivre_orders_results .......... [RUN]
[2025-06-05T19:46:11.489+0000] {logging_mixin.py:190} INFO - 19:46:11  3 of 11 START sql incremental model sales.shopee_new_id ........................ [RUN]
[2025-06-05T19:46:11.717+0000] {logging_mixin.py:190} INFO - 19:46:11  1 of 11 ERROR creating sql incremental model sales.dim_shopee_product .......... [ERROR in 0.22s]
[2025-06-05T19:46:11.888+0000] {logging_mixin.py:190} INFO - 19:46:11  3 of 11 OK created sql incremental model sales.shopee_new_id ................... [MERGE 0 in 0.39s]
[2025-06-05T19:46:11.894+0000] {logging_mixin.py:190} INFO - 19:46:11  2 of 11 OK created sql incremental model sales.mercadolivre_orders_results ..... [MERGE 190 in 0.40s]
[2025-06-05T19:46:11.898+0000] {logging_mixin.py:190} INFO - 19:46:11  4 of 11 START sql incremental model sales.shopee_orders_results ................ [RUN]
[2025-06-05T19:46:11.903+0000] {logging_mixin.py:190} INFO - 19:46:11  5 of 11 START sql incremental model sales.dim_mercadolivre_buyer ............... [RUN]
[2025-06-05T19:46:11.905+0000] {logging_mixin.py:190} INFO - 19:46:11  6 of 11 START sql incremental model sales.dim_mercadolivre_date ................ [RUN]
[2025-06-05T19:46:11.907+0000] {logging_mixin.py:190} INFO - 19:46:11  7 of 11 START sql incremental model sales.dim_mercadolivre_orders_status ....... [RUN]
[2025-06-05T19:46:12.188+0000] {logging_mixin.py:190} INFO - 19:46:12  4 of 11 OK created sql incremental model sales.shopee_orders_results ........... [MERGE 0 in 0.28s]
[2025-06-05T19:46:12.212+0000] {logging_mixin.py:190} INFO - 19:46:12  8 of 11 START sql incremental model sales.dim_mercadolivre_product ............. [RUN]
[2025-06-05T19:46:12.227+0000] {logging_mixin.py:190} INFO - 19:46:12  7 of 11 OK created sql incremental model sales.dim_mercadolivre_orders_status .. [MERGE 190 in 0.30s]
[2025-06-05T19:46:12.250+0000] {logging_mixin.py:190} INFO - 19:46:12  5 of 11 OK created sql incremental model sales.dim_mercadolivre_buyer .......... [MERGE 188 in 0.33s]
[2025-06-05T19:46:12.252+0000] {logging_mixin.py:190} INFO - 19:46:12  6 of 11 OK created sql incremental model sales.dim_mercadolivre_date ........... [MERGE 190 in 0.34s]
[2025-06-05T19:46:12.258+0000] {logging_mixin.py:190} INFO - 19:46:12  9 of 11 START sql incremental model sales.dim_shopee_buyer ..................... [RUN]
[2025-06-05T19:46:12.275+0000] {logging_mixin.py:190} INFO - 19:46:12  10 of 11 START sql incremental model sales.dim_shopee_date ..................... [RUN]
[2025-06-05T19:46:12.278+0000] {logging_mixin.py:190} INFO - 19:46:12  11 of 11 START sql incremental model sales.dim_shopee_orders_status ............ [RUN]
[2025-06-05T19:46:12.519+0000] {logging_mixin.py:190} INFO - 19:46:12  8 of 11 OK created sql incremental model sales.dim_mercadolivre_product ........ [MERGE 65 in 0.30s]
[2025-06-05T19:46:12.542+0000] {logging_mixin.py:190} INFO - 19:46:12  9 of 11 OK created sql incremental model sales.dim_shopee_buyer ................ [MERGE 0 in 0.27s]
[2025-06-05T19:46:12.553+0000] {logging_mixin.py:190} INFO - 19:46:12  11 of 11 OK created sql incremental model sales.dim_shopee_orders_status ....... [MERGE 0 in 0.27s]
[2025-06-05T19:46:12.555+0000] {logging_mixin.py:190} INFO - 19:46:12  10 of 11 OK created sql incremental model sales.dim_shopee_date ................ [MERGE 0 in 0.27s]
[2025-06-05T19:46:12.581+0000] {logging_mixin.py:190} INFO - 19:46:12
[2025-06-05T19:46:12.583+0000] {logging_mixin.py:190} INFO - 19:46:12  Finished running 11 incremental models in 0 hours 0 minutes and 1.23 seconds (1.23s).
[2025-06-05T19:46:12.667+0000] {logging_mixin.py:190} INFO - 19:46:12
[2025-06-05T19:46:12.669+0000] {logging_mixin.py:190} INFO - 19:46:12  Completed with 1 error, 0 partial successes, and 0 warnings:
[2025-06-05T19:46:12.670+0000] {logging_mixin.py:190} INFO - 19:46:12
[2025-06-05T19:46:12.671+0000] {logging_mixin.py:190} INFO - 19:46:12    Database Error in model dim_shopee_product (models/core/dim_shopee_product.sql)
  missing FROM-clause entry for table "orders_results"
  LINE 35:                 AND orders_results.ld_timestamp  > (SELECT M...
                               ^
[2025-06-05T19:46:12.673+0000] {logging_mixin.py:190} INFO - 19:46:12
[2025-06-05T19:46:12.675+0000] {logging_mixin.py:190} INFO - 19:46:12  Done. PASS=10 WARN=0 ERROR=1 SKIP=0 TOTAL=11
[2025-06-05T19:46:13.525+0000] {logging_mixin.py:190} INFO - dbt run failed!
[2025-06-05T19:46:13.526+0000] {logging_mixin.py:190} INFO - None
[2025-06-05T19:46:13.527+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt_files/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-06-05T19:46:13.541+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=04_transform_data, task_id=run_dbt, run_id=manual__2025-06-05T19:45:58.567017+00:00, execution_date=20250605T194558, start_date=20250605T194607, end_date=20250605T194613
[2025-06-05T19:46:13.554+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-05T19:46:13.555+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 347 for task run_dbt (dbt run failed; 2262)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dbt_files/run_dbt.py", line 22, in transform_data
    raise RuntimeError("dbt run failed")
RuntimeError: dbt run failed
[2025-06-05T19:46:13.571+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-05T19:46:13.589+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-05T19:46:13.592+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
