[2025-06-23T17:05:37.035+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-23T17:05:37.053+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 01_extract_data_prod.ml_access_token manual__2025-06-23T17:05:35.318603+00:00 [queued]>
[2025-06-23T17:05:37.060+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 01_extract_data_prod.ml_access_token manual__2025-06-23T17:05:35.318603+00:00 [queued]>
[2025-06-23T17:05:37.062+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-23T17:05:37.073+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ml_access_token> on 2025-06-23 17:05:35.318603+00:00
[2025-06-23T17:05:37.077+0000] {standard_task_runner.py:72} INFO - Started process 586 to run task
[2025-06-23T17:05:37.080+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '01_extract_data_prod', 'ml_access_token', 'manual__2025-06-23T17:05:35.318603+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/01_extract_dag_prod.py', '--cfg-path', '/tmp/tmpzcrnhjv0']
[2025-06-23T17:05:37.082+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask ml_access_token
[2025-06-23T17:05:37.132+0000] {task_command.py:467} INFO - Running <TaskInstance: 01_extract_data_prod.ml_access_token manual__2025-06-23T17:05:35.318603+00:00 [running]> on host b208c9761688
[2025-06-23T17:05:37.203+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='01_extract_data_prod' AIRFLOW_CTX_TASK_ID='ml_access_token' AIRFLOW_CTX_EXECUTION_DATE='2025-06-23T17:05:35.318603+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-23T17:05:35.318603+00:00'
[2025-06-23T17:05:37.204+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-23T17:05:37.469+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/extraction/mercadolivre/get_access_token.py", line 42, in get_access_token
    set_key(env_path, "ACCESS_TOKEN", token_data["access_token"], encoding='utf-8')
KeyError: 'access_token'
[2025-06-23T17:05:37.485+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=01_extract_data_prod, task_id=ml_access_token, run_id=manual__2025-06-23T17:05:35.318603+00:00, execution_date=20250623T170535, start_date=20250623T170537, end_date=20250623T170537
[2025-06-23T17:05:37.494+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-23T17:05:37.495+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task ml_access_token ('access_token'; 586)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/extraction/mercadolivre/get_access_token.py", line 42, in get_access_token
    set_key(env_path, "ACCESS_TOKEN", token_data["access_token"], encoding='utf-8')
KeyError: 'access_token'
[2025-06-23T17:05:37.536+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-23T17:05:37.557+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-23T17:05:37.562+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
